   <header>
        <h1>Docman</h1>
        <p>The Swiss Army Knife for Drupal Multisite Docroot Management and Deployment</p>

        <p class="view"><a href="https://github.com/Adyax/docman">View the Project on GitHub <small>Adyax/docman</small></a></p>

        <ul>
          <li><a href="https://github.com/Adyax/docman/zipball/master">Download <strong>ZIP File</strong></a></li>
          <li><a href="https://github.com/Adyax/docman/tarball/master">Download <strong>TAR Ball</strong></a></li>
          <li><a href="https://github.com/Adyax/docman">View On <strong>GitHub</strong></a></li>
        </ul>
      </header>