---
scenario: one-to-one
components:
  master:
    type: root_chain
    root_repo_states:
      development:
        type: branch
        version: develop
      staging:
        type: branch
        version: staging
      stable:
        type: branch
        version: master
    states:
      development:
        type: branch
        version: develop
      staging:
        type: branch
        version: staging
      stable:
        source:
          type: :retrieve_from_repo
          repo: :project_repo
          branch: state_stable
          file: info.yaml
    hooks:
      builder:
        after_execute:
          - type: :yaml_execute
            environments: [dev, staging, stable]
            commands:
              - rm -f .gitignore
              - cp -f .gitignore.docroot .gitignore

