---
deploy_targets:
  local:
    handler: :common_deployer
    builders:
      root:
        handler: :dir_builder
      root_chain:
        handler: :git_direct_builder
      drupal:
        handler: :drupal_drush_builder
      repo:
        handler: :git_direct_builder
      dir:
        handler: :dir_builder
      symlink:
        handler: :symlink_builder
    states:
      development: local
      staging: local
      stable: local
  git_target:
    handler: :git_deployer
    builders:
      root:
        handler: :git_direct_builder
        hooks:
          builder:
            after_execute:
              - type: :git_commit
                order: 100
                execution_dir: $PROJECT$
      root_chain:
        handler: :git_root_chain_builder
        hooks:
          builder:
            after_execute:
              - type: :git_commit
                order: 100
                execution_dir: $PROJECT$
      drupal:
        handler: :drupal_drush_builder
        hooks:
          builder:
            after_execute:
              - type: :git_commit
                order: 100
                execution_dir: $PROJECT$
      repo:
        handler: :git_strip_builder
        hooks:
          builder:
            before_execute:
              - type: :git_pull
                execution_dir: $PROJECT$
            after_execute:
              - type: :git_commit
                order: 100
                execution_dir: $PROJECT$
      dir:
        handler: :dir_builder
        hooks:
          builder:
            after_execute:
              - type: :git_commit
                order: 100
                execution_dir: $PROJECT$
      symlink:
        handler: :symlink_builder
        hooks:
          builder:
            after_execute:
              - type: :git_commit
                order: 100
                execution_dir: $PROJECT$
    states:
      development: dev
      staging: test
      stable: prod
environments:
  local:
    deploy_target: local
    state: development
    clean_changed: true
