---
deploy_targets:
  local:
    handler: :common_deployer
    builders:
      root:
        handler: :dir_builder
      drupal:
        handler: :drupal_drush_builder
      repo:
        handler: :git_direct_builder
      dir:
        handler: :dir_builder
    environments:
      development: local
      staging: local
      stable: local
  acquia:
    handler: :git_deployer
    builders:
      root:
        handler: :git_direct_builder
        hooks:
          builder:
            after_execute:
              - type: :git_commit
                execution_dir: $PROJECT$
      drupal:
        handler: :drupal_drush_builder
        hooks:
          builder:
            after_execute:
              - type: :git_commit
                execution_dir: $PROJECT$
      repo:
        handler: :git_strip_builder
        hooks:
          builder:
            after_execute:
              - type: :git_commit
                execution_dir: $PROJECT$
      dir:
        handler: :dir_builder
        hooks:
          builder:
            after_execute:
              - type: :git_commit
                execution_dir: $PROJECT$
    environments:
      development: dev
      staging: stg
      stable: prod
