---
deploy_targets:
  local:
    handler: :common_deployer
    builders:
      root:
        handler: :dir
      drupal:
        handler: :drupal_drush
      repo:
        handler: :git_direct
      dir:
        handler: :dir
  acquia:
    handler: :git_deployer
    deploy_action: git_push
    builders:
      root:
        handler: :git_direct
        after:
          - :git_commit
      drupal:
        handler: :drupal_drush
        after:
          - :git_commit
      repo:
        handler: :git_strip
        after:
          - :git_commit
      dir:
        handler: :dir
        after:
          - :git_commit
environments:
