<h2>Overview</h2>
<p>Introducing Docman: the Swiss Army Knife for Drupal multisite docroot management and deployment. Docman acts as a layer between your docroot - usually a git repository somewhere, but not limited to it- and multiple vendors working on different websites using your standards and predefined sets of modules.</p>

<p>Remember how hosting sales teams always tried to push you to buy more docroots "because otherwise it would be hard to manage websites in a Drupal multisite environment"? Docman can simplify your life so you will be able to stick to one docroot and multiple independent websites in it using the same Drupal core.</p>

<p>Have you ever tried to oblige different vendors to work with one Drupal core for completely different websites, inside a multisite environment, without making them break everything and with clear deployment schema? Find out how docman can make the once daunting task of multisite deployment more efficient.</p>

<p>Does the governance of multiple projects in one multisite environment scare you? Docman has hooks, like Drupal, to launch your tests whenever needed and for each website in multisite environment independently.</p>

<p>Real-world example:</p>

<ul>
<li>You have a docroot at Acquia Cloud</li>
<li>You have a small governance team setting up standards (Drupal core, list of contrib modules)</li>
<li>You have 3 vendors working on three different websites in multisite environment</li>
</ul>
