<h2><a name="supported-ruby-versions" class="anchor" href="#supported-ruby-versions"><span class="octicon octicon-link"></span></a>Supported Ruby Versions</h2>

<p>This library aims to support and is tested against the following Ruby
implementations:</p>

<ul>
<li>Ruby 1.9.2</li>
<li>Ruby 1.9.3</li>
<li>Ruby 2.0.0</li>
<li>Ruby 2.1.0</li>
</ul><p>If something doesn't work on one of these Ruby versions, it's a bug.</p>

<p>This library may inadvertently work (or seem to work) on other Ruby
implementations, however support will only be provided for the versions listed
above.</p>

<p>If you would like this library to support another Ruby version, you may
volunteer to be a maintainer. Being a maintainer entails making sure all tests
run and pass on that implementation. When something breaks on your
implementation, you will be responsible for providing patches in a timely
fashion. If critical issues for a particular implementation exist at the time
of a major release, support for that Ruby version may be dropped.</p>